### ISSUE TITLE
Using Docker

### ISSUE THREAD

**Issue by vasily-kartashov** [Anniepoo/swiplwebtut#36]
When running swipl in a docker container, the service cannot be reached from the host.

here's my `docker-compose.yml`:

```yaml
version: '3'
services:
  swipl:
    image: swipl
    volumes:
      - type: bind
        source: ./app
        target: /app
    working_dir: /app
    ports:
      - 8080:8080
```

and the `server.pl`:

```prolog
:- use_module(library(http/thread_httpd)).
:- use_module(library(http/http_dispatch)).

server(Port) :-
    http_server(http_dispatch, [port(Port)]).

:- http_handler(/, say_hi, []).

say_hi(_Request) :-
    format('Content-Type: text/plain~n~n'),
    format('Hello!~n').
```

When running `curl localhost:8080` from outside, the host doesn't answer. But when you log it into the running container with ` docker exec -it ... sh`, the same curl command shows that the app is working:

```
# apt update && apt install curl
# curl localhost:8080/
Hello!
```
